using System.Collections;
using System.Collections.Generic;
using UnityEngine;

//using the namespace Photon.Pun
using Photon.Pun;
using System;
using System.Runtime.CompilerServices;


//Inheriting from the MonoBehaviourPunCallbacks.
public class Launcher : MonoBehaviourPunCallbacks
{
    // Start is called before the first frame update
    void Start()
    {
        Debug.Log("Connecting to Master...");
        //connect to the photon master server using the settings file, "Photon Server Settings" generated by the photon package.
        PhotonNetwork.ConnectUsingSettings();
    }


    //after connection is made to the master server:
    public override void OnConnectedToMaster()
    {
        Debug.Log("Connected to master.");
        Debug.Log("Connecting to Lobby...");
        //join lobby after connection is secured to the master server to be able to connect to rooms.
        PhotonNetwork.JoinLobby();
    }

    public override void OnJoinedLobby()
    {
        Debug.Log("Joined Lobby!");
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
